//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.walgreens.services.erx.dataentrybypassservice.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CalculatedValues complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalculatedValues">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="refillsRemainingEntered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dailyDose" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daysOfSupply" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="expirationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="maxDaysToFill" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="refillBeforeDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="refillsRemaining" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="quantityDispensed" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="quantityRemaining" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numberOfFillsPrescribed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="totalDefaultDaysOfSupply" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalculatedValues", propOrder = {
    "refillsRemainingEntered",
    "dailyDose",
    "daysOfSupply",
    "expirationDate",
    "maxDaysToFill",
    "refillBeforeDate",
    "refillsRemaining",
    "quantity",
    "quantityDispensed",
    "quantityRemaining",
    "numberOfFillsPrescribed",
    "totalDefaultDaysOfSupply"
})
public class CalculatedValues {

    protected String refillsRemainingEntered;
    protected int dailyDose;
    protected int daysOfSupply;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expirationDate;
    protected int maxDaysToFill;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar refillBeforeDate;
    @XmlElement(required = true)
    protected String refillsRemaining;
    protected double quantity;
    protected double quantityDispensed;
    @XmlElement(required = true)
    protected String quantityRemaining;
    protected int numberOfFillsPrescribed;
    protected int totalDefaultDaysOfSupply;

    /**
     * Gets the value of the refillsRemainingEntered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefillsRemainingEntered() {
        return refillsRemainingEntered;
    }

    /**
     * Sets the value of the refillsRemainingEntered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefillsRemainingEntered(String value) {
        this.refillsRemainingEntered = value;
    }

    /**
     * Gets the value of the dailyDose property.
     * 
     */
    public int getDailyDose() {
        return dailyDose;
    }

    /**
     * Sets the value of the dailyDose property.
     * 
     */
    public void setDailyDose(int value) {
        this.dailyDose = value;
    }

    /**
     * Gets the value of the daysOfSupply property.
     * 
     */
    public int getDaysOfSupply() {
        return daysOfSupply;
    }

    /**
     * Sets the value of the daysOfSupply property.
     * 
     */
    public void setDaysOfSupply(int value) {
        this.daysOfSupply = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the maxDaysToFill property.
     * 
     */
    public int getMaxDaysToFill() {
        return maxDaysToFill;
    }

    /**
     * Sets the value of the maxDaysToFill property.
     * 
     */
    public void setMaxDaysToFill(int value) {
        this.maxDaysToFill = value;
    }

    /**
     * Gets the value of the refillBeforeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRefillBeforeDate() {
        return refillBeforeDate;
    }

    /**
     * Sets the value of the refillBeforeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRefillBeforeDate(XMLGregorianCalendar value) {
        this.refillBeforeDate = value;
    }

    /**
     * Gets the value of the refillsRemaining property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefillsRemaining() {
        return refillsRemaining;
    }

    /**
     * Sets the value of the refillsRemaining property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefillsRemaining(String value) {
        this.refillsRemaining = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public double getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(double value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the quantityDispensed property.
     * 
     */
    public double getQuantityDispensed() {
        return quantityDispensed;
    }

    /**
     * Sets the value of the quantityDispensed property.
     * 
     */
    public void setQuantityDispensed(double value) {
        this.quantityDispensed = value;
    }

    /**
     * Gets the value of the quantityRemaining property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantityRemaining() {
        return quantityRemaining;
    }

    /**
     * Sets the value of the quantityRemaining property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantityRemaining(String value) {
        this.quantityRemaining = value;
    }

    /**
     * Gets the value of the numberOfFillsPrescribed property.
     * 
     */
    public int getNumberOfFillsPrescribed() {
        return numberOfFillsPrescribed;
    }

    /**
     * Sets the value of the numberOfFillsPrescribed property.
     * 
     */
    public void setNumberOfFillsPrescribed(int value) {
        this.numberOfFillsPrescribed = value;
    }

    /**
     * Gets the value of the totalDefaultDaysOfSupply property.
     * 
     */
    public int getTotalDefaultDaysOfSupply() {
        return totalDefaultDaysOfSupply;
    }

    /**
     * Sets the value of the totalDefaultDaysOfSupply property.
     * 
     */
    public void setTotalDefaultDaysOfSupply(int value) {
        this.totalDefaultDaysOfSupply = value;
    }

}
