//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.walgreens.services.erx.dataentrybypassservice.ds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Drug complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Drug">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="drugId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}DrugType" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nationalDrugCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transmittedQuantityIsMultipleOfPackageSize" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="transmittedQuantityEqualsPackageSize" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="onTherapeuticInclusionList" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="calculatedValues" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}CalculatedValues" minOccurs="0"/>
 *         &lt;element name="preferredGenericProduct" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}PreferredGenericProduct" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="substitutionIndicator" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}substitutionIndicator" minOccurs="0"/>
 *         &lt;element name="status" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}statusType"/>
 *         &lt;element name="compoundDrug" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="drugClass" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}DrugClassType" minOccurs="0"/>
 *         &lt;element name="federalDrugConstraint" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}DrugConstraint" minOccurs="0"/>
 *         &lt;element name="stateDrugConstraint" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}DrugConstraint" minOccurs="0"/>
 *         &lt;element name="defaultDaysOfSupply" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="defaultSig" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dispensingRestriction" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="translatedDosageForm" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}DosageFormType"/>
 *         &lt;element name="dosesPerPackage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="expirationDays" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="excluded" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="overridden" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="genericProductIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="limitedDistributionCode" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="linked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="maintenanceDrug" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="minimumDispensingQuantity" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="orangeBookRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="packageSize" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="packageQuantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="packageType" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}PackageType"/>
 *         &lt;element name="dosageFormCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="routeOfAdministration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="storePreferredDrugId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="therapeuticClass" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="validQuantityQualifier" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="quantityUOM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="validTherapeuticClass" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="totalNumberOfPackages" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="categories" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}ProductCategory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="multiHitIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="walgreenAcquisitionCost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Drug", propOrder = {
    "dataSource",
    "drugId",
    "type",
    "name",
    "nationalDrugCode",
    "transmittedQuantityIsMultipleOfPackageSize",
    "transmittedQuantityEqualsPackageSize",
    "onTherapeuticInclusionList",
    "calculatedValues",
    "preferredGenericProduct",
    "substitutionIndicator",
    "status",
    "compoundDrug",
    "drugClass",
    "federalDrugConstraint",
    "stateDrugConstraint",
    "defaultDaysOfSupply",
    "defaultSig",
    "dispensingRestriction",
    "translatedDosageForm",
    "dosesPerPackage",
    "expirationDays",
    "excluded",
    "overridden",
    "genericProductIdentifier",
    "limitedDistributionCode",
    "linked",
    "maintenanceDrug",
    "minimumDispensingQuantity",
    "orangeBookRating",
    "packageSize",
    "packageQuantity",
    "packageType",
    "dosageFormCode",
    "routeOfAdministration",
    "storePreferredDrugId",
    "therapeuticClass",
    "validQuantityQualifier",
    "quantityUOM",
    "validTherapeuticClass",
    "totalNumberOfPackages",
    "categories",
    "multiHitIndicator",
    "walgreenAcquisitionCost"
})
public class Drug {

    protected String dataSource;
    protected String drugId;
    protected DrugType type;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String nationalDrugCode;
    protected boolean transmittedQuantityIsMultipleOfPackageSize;
    protected boolean transmittedQuantityEqualsPackageSize;
    protected boolean onTherapeuticInclusionList;
    protected CalculatedValues calculatedValues;
    protected List<PreferredGenericProduct> preferredGenericProduct;
    protected SubstitutionIndicator substitutionIndicator;
    @XmlElement(required = true)
    protected StatusType status;
    protected boolean compoundDrug;
    protected DrugClassType drugClass;
    protected DrugConstraint federalDrugConstraint;
    protected DrugConstraint stateDrugConstraint;
    protected Integer defaultDaysOfSupply;
    protected String defaultSig;
    protected Boolean dispensingRestriction;
    @XmlElement(required = true)
    protected DosageFormType translatedDosageForm;
    protected Integer dosesPerPackage;
    protected Integer expirationDays;
    protected boolean excluded;
    protected boolean overridden;
    protected String genericProductIdentifier;
    protected Boolean limitedDistributionCode;
    protected Boolean linked;
    protected Boolean maintenanceDrug;
    protected double minimumDispensingQuantity;
    protected String orangeBookRating;
    protected double packageSize;
    protected int packageQuantity;
    @XmlElement(required = true)
    protected PackageType packageType;
    protected String dosageFormCode;
    protected String routeOfAdministration;
    protected String storePreferredDrugId;
    protected int therapeuticClass;
    protected Boolean validQuantityQualifier;
    protected String quantityUOM;
    protected Boolean validTherapeuticClass;
    protected Double totalNumberOfPackages;
    protected List<ProductCategory> categories;
    protected String multiHitIndicator;
    protected double walgreenAcquisitionCost;

    /**
     * Gets the value of the dataSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * Sets the value of the dataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSource(String value) {
        this.dataSource = value;
    }

    /**
     * Gets the value of the drugId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugId() {
        return drugId;
    }

    /**
     * Sets the value of the drugId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugId(String value) {
        this.drugId = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link DrugType }
     *     
     */
    public DrugType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrugType }
     *     
     */
    public void setType(DrugType value) {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nationalDrugCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalDrugCode() {
        return nationalDrugCode;
    }

    /**
     * Sets the value of the nationalDrugCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalDrugCode(String value) {
        this.nationalDrugCode = value;
    }

    /**
     * Gets the value of the transmittedQuantityIsMultipleOfPackageSize property.
     * 
     */
    public boolean isTransmittedQuantityIsMultipleOfPackageSize() {
        return transmittedQuantityIsMultipleOfPackageSize;
    }

    /**
     * Sets the value of the transmittedQuantityIsMultipleOfPackageSize property.
     * 
     */
    public void setTransmittedQuantityIsMultipleOfPackageSize(boolean value) {
        this.transmittedQuantityIsMultipleOfPackageSize = value;
    }

    /**
     * Gets the value of the transmittedQuantityEqualsPackageSize property.
     * 
     */
    public boolean isTransmittedQuantityEqualsPackageSize() {
        return transmittedQuantityEqualsPackageSize;
    }

    /**
     * Sets the value of the transmittedQuantityEqualsPackageSize property.
     * 
     */
    public void setTransmittedQuantityEqualsPackageSize(boolean value) {
        this.transmittedQuantityEqualsPackageSize = value;
    }

    /**
     * Gets the value of the onTherapeuticInclusionList property.
     * 
     */
    public boolean isOnTherapeuticInclusionList() {
        return onTherapeuticInclusionList;
    }

    /**
     * Sets the value of the onTherapeuticInclusionList property.
     * 
     */
    public void setOnTherapeuticInclusionList(boolean value) {
        this.onTherapeuticInclusionList = value;
    }

    /**
     * Gets the value of the calculatedValues property.
     * 
     * @return
     *     possible object is
     *     {@link CalculatedValues }
     *     
     */
    public CalculatedValues getCalculatedValues() {
        return calculatedValues;
    }

    /**
     * Sets the value of the calculatedValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculatedValues }
     *     
     */
    public void setCalculatedValues(CalculatedValues value) {
        this.calculatedValues = value;
    }

    /**
     * Gets the value of the preferredGenericProduct property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preferredGenericProduct property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreferredGenericProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PreferredGenericProduct }
     * 
     * 
     */
    public List<PreferredGenericProduct> getPreferredGenericProduct() {
        if (preferredGenericProduct == null) {
            preferredGenericProduct = new ArrayList<PreferredGenericProduct>();
        }
        return this.preferredGenericProduct;
    }

    /**
     * Gets the value of the substitutionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link SubstitutionIndicator }
     *     
     */
    public SubstitutionIndicator getSubstitutionIndicator() {
        return substitutionIndicator;
    }

    /**
     * Sets the value of the substitutionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubstitutionIndicator }
     *     
     */
    public void setSubstitutionIndicator(SubstitutionIndicator value) {
        this.substitutionIndicator = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the compoundDrug property.
     * 
     */
    public boolean isCompoundDrug() {
        return compoundDrug;
    }

    /**
     * Sets the value of the compoundDrug property.
     * 
     */
    public void setCompoundDrug(boolean value) {
        this.compoundDrug = value;
    }

    /**
     * Gets the value of the drugClass property.
     * 
     * @return
     *     possible object is
     *     {@link DrugClassType }
     *     
     */
    public DrugClassType getDrugClass() {
        return drugClass;
    }

    /**
     * Sets the value of the drugClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrugClassType }
     *     
     */
    public void setDrugClass(DrugClassType value) {
        this.drugClass = value;
    }

    /**
     * Gets the value of the federalDrugConstraint property.
     * 
     * @return
     *     possible object is
     *     {@link DrugConstraint }
     *     
     */
    public DrugConstraint getFederalDrugConstraint() {
        return federalDrugConstraint;
    }

    /**
     * Sets the value of the federalDrugConstraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrugConstraint }
     *     
     */
    public void setFederalDrugConstraint(DrugConstraint value) {
        this.federalDrugConstraint = value;
    }

    /**
     * Gets the value of the stateDrugConstraint property.
     * 
     * @return
     *     possible object is
     *     {@link DrugConstraint }
     *     
     */
    public DrugConstraint getStateDrugConstraint() {
        return stateDrugConstraint;
    }

    /**
     * Sets the value of the stateDrugConstraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrugConstraint }
     *     
     */
    public void setStateDrugConstraint(DrugConstraint value) {
        this.stateDrugConstraint = value;
    }

    /**
     * Gets the value of the defaultDaysOfSupply property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDefaultDaysOfSupply() {
        return defaultDaysOfSupply;
    }

    /**
     * Sets the value of the defaultDaysOfSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefaultDaysOfSupply(Integer value) {
        this.defaultDaysOfSupply = value;
    }

    /**
     * Gets the value of the defaultSig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultSig() {
        return defaultSig;
    }

    /**
     * Sets the value of the defaultSig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultSig(String value) {
        this.defaultSig = value;
    }

    /**
     * Gets the value of the dispensingRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDispensingRestriction() {
        return dispensingRestriction;
    }

    /**
     * Sets the value of the dispensingRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDispensingRestriction(Boolean value) {
        this.dispensingRestriction = value;
    }

    /**
     * Gets the value of the translatedDosageForm property.
     * 
     * @return
     *     possible object is
     *     {@link DosageFormType }
     *     
     */
    public DosageFormType getTranslatedDosageForm() {
        return translatedDosageForm;
    }

    /**
     * Sets the value of the translatedDosageForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DosageFormType }
     *     
     */
    public void setTranslatedDosageForm(DosageFormType value) {
        this.translatedDosageForm = value;
    }

    /**
     * Gets the value of the dosesPerPackage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDosesPerPackage() {
        return dosesPerPackage;
    }

    /**
     * Sets the value of the dosesPerPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDosesPerPackage(Integer value) {
        this.dosesPerPackage = value;
    }

    /**
     * Gets the value of the expirationDays property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExpirationDays() {
        return expirationDays;
    }

    /**
     * Sets the value of the expirationDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExpirationDays(Integer value) {
        this.expirationDays = value;
    }

    /**
     * Gets the value of the excluded property.
     * 
     */
    public boolean isExcluded() {
        return excluded;
    }

    /**
     * Sets the value of the excluded property.
     * 
     */
    public void setExcluded(boolean value) {
        this.excluded = value;
    }

    /**
     * Gets the value of the overridden property.
     * 
     */
    public boolean isOverridden() {
        return overridden;
    }

    /**
     * Sets the value of the overridden property.
     * 
     */
    public void setOverridden(boolean value) {
        this.overridden = value;
    }

    /**
     * Gets the value of the genericProductIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericProductIdentifier() {
        return genericProductIdentifier;
    }

    /**
     * Sets the value of the genericProductIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericProductIdentifier(String value) {
        this.genericProductIdentifier = value;
    }

    /**
     * Gets the value of the limitedDistributionCode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLimitedDistributionCode() {
        return limitedDistributionCode;
    }

    /**
     * Sets the value of the limitedDistributionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLimitedDistributionCode(Boolean value) {
        this.limitedDistributionCode = value;
    }

    /**
     * Gets the value of the linked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLinked() {
        return linked;
    }

    /**
     * Sets the value of the linked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLinked(Boolean value) {
        this.linked = value;
    }

    /**
     * Gets the value of the maintenanceDrug property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMaintenanceDrug() {
        return maintenanceDrug;
    }

    /**
     * Sets the value of the maintenanceDrug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMaintenanceDrug(Boolean value) {
        this.maintenanceDrug = value;
    }

    /**
     * Gets the value of the minimumDispensingQuantity property.
     * 
     */
    public double getMinimumDispensingQuantity() {
        return minimumDispensingQuantity;
    }

    /**
     * Sets the value of the minimumDispensingQuantity property.
     * 
     */
    public void setMinimumDispensingQuantity(double value) {
        this.minimumDispensingQuantity = value;
    }

    /**
     * Gets the value of the orangeBookRating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrangeBookRating() {
        return orangeBookRating;
    }

    /**
     * Sets the value of the orangeBookRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrangeBookRating(String value) {
        this.orangeBookRating = value;
    }

    /**
     * Gets the value of the packageSize property.
     * 
     */
    public double getPackageSize() {
        return packageSize;
    }

    /**
     * Sets the value of the packageSize property.
     * 
     */
    public void setPackageSize(double value) {
        this.packageSize = value;
    }

    /**
     * Gets the value of the packageQuantity property.
     * 
     */
    public int getPackageQuantity() {
        return packageQuantity;
    }

    /**
     * Sets the value of the packageQuantity property.
     * 
     */
    public void setPackageQuantity(int value) {
        this.packageQuantity = value;
    }

    /**
     * Gets the value of the packageType property.
     * 
     * @return
     *     possible object is
     *     {@link PackageType }
     *     
     */
    public PackageType getPackageType() {
        return packageType;
    }

    /**
     * Sets the value of the packageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageType }
     *     
     */
    public void setPackageType(PackageType value) {
        this.packageType = value;
    }

    /**
     * Gets the value of the dosageFormCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDosageFormCode() {
        return dosageFormCode;
    }

    /**
     * Sets the value of the dosageFormCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDosageFormCode(String value) {
        this.dosageFormCode = value;
    }

    /**
     * Gets the value of the routeOfAdministration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteOfAdministration() {
        return routeOfAdministration;
    }

    /**
     * Sets the value of the routeOfAdministration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteOfAdministration(String value) {
        this.routeOfAdministration = value;
    }

    /**
     * Gets the value of the storePreferredDrugId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorePreferredDrugId() {
        return storePreferredDrugId;
    }

    /**
     * Sets the value of the storePreferredDrugId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorePreferredDrugId(String value) {
        this.storePreferredDrugId = value;
    }

    /**
     * Gets the value of the therapeuticClass property.
     * 
     */
    public int getTherapeuticClass() {
        return therapeuticClass;
    }

    /**
     * Sets the value of the therapeuticClass property.
     * 
     */
    public void setTherapeuticClass(int value) {
        this.therapeuticClass = value;
    }

    /**
     * Gets the value of the validQuantityQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isValidQuantityQualifier() {
        return validQuantityQualifier;
    }

    /**
     * Sets the value of the validQuantityQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValidQuantityQualifier(Boolean value) {
        this.validQuantityQualifier = value;
    }

    /**
     * Gets the value of the quantityUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantityUOM() {
        return quantityUOM;
    }

    /**
     * Sets the value of the quantityUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantityUOM(String value) {
        this.quantityUOM = value;
    }

    /**
     * Gets the value of the validTherapeuticClass property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isValidTherapeuticClass() {
        return validTherapeuticClass;
    }

    /**
     * Sets the value of the validTherapeuticClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValidTherapeuticClass(Boolean value) {
        this.validTherapeuticClass = value;
    }

    /**
     * Gets the value of the totalNumberOfPackages property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalNumberOfPackages() {
        return totalNumberOfPackages;
    }

    /**
     * Sets the value of the totalNumberOfPackages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalNumberOfPackages(Double value) {
        this.totalNumberOfPackages = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductCategory }
     * 
     * 
     */
    public List<ProductCategory> getCategories() {
        if (categories == null) {
            categories = new ArrayList<ProductCategory>();
        }
        return this.categories;
    }

    /**
     * Gets the value of the multiHitIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiHitIndicator() {
        return multiHitIndicator;
    }

    /**
     * Sets the value of the multiHitIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiHitIndicator(String value) {
        this.multiHitIndicator = value;
    }

    /**
     * Gets the value of the walgreenAcquisitionCost property.
     * 
     */
    public double getWalgreenAcquisitionCost() {
        return walgreenAcquisitionCost;
    }

    /**
     * Sets the value of the walgreenAcquisitionCost property.
     * 
     */
    public void setWalgreenAcquisitionCost(double value) {
        this.walgreenAcquisitionCost = value;
    }

}
