//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.walgreens.services.erx.dataentrybypassservice.ds;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ErxDecisionServices", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ErxDecisionServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.walgreens.services.erx.dataentrybypassservice.ds.ErxTransaction
     */
    @WebMethod(action = "urn:executeDrugSelection")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDrugSelection", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetDrugSelection")
    @ResponseWrapper(localName = "getDrugSelectionResponse", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetDrugSelectionResponse")
    @Action(input = "urn:executeDrugSelection", output = "http://services.walgreens.com/erx/DataEntryByPassService/ds/ErxDecisionServices/getDrugSelectionResponse")
    public ErxTransaction getDrugSelection(
        @WebParam(name = "arg0", targetNamespace = "")
        ErxTransaction arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.walgreens.services.erx.dataentrybypassservice.ds.ErxTransaction
     */
    @WebMethod(action = "urn:executeDrugSelectionAndQuantity")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDrugSelectionAndQuantity", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetDrugSelectionAndQuantity")
    @ResponseWrapper(localName = "getDrugSelectionAndQuantityResponse", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetDrugSelectionAndQuantityResponse")
    @Action(input = "urn:executeDrugSelectionAndQuantity", output = "http://services.walgreens.com/erx/DataEntryByPassService/ds/ErxDecisionServices/getDrugSelectionAndQuantityResponse")
    public ErxTransaction getDrugSelectionAndQuantity(
        @WebParam(name = "arg0", targetNamespace = "")
        ErxTransaction arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.walgreens.services.erx.dataentrybypassservice.ds.ErxTransaction
     */
    @WebMethod(action = "urn:executeQuantity")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuantity", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetQuantity")
    @ResponseWrapper(localName = "getQuantityResponse", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetQuantityResponse")
    @Action(input = "urn:executeQuantity", output = "http://services.walgreens.com/erx/DataEntryByPassService/ds/ErxDecisionServices/getQuantityResponse")
    public ErxTransaction getQuantity(
        @WebParam(name = "arg0", targetNamespace = "")
        ErxTransaction arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.walgreens.services.erx.dataentrybypassservice.ds.ErxTransaction
     */
    @WebMethod(action = "urn:executeDaySupply")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDaySupply", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetDaySupply")
    @ResponseWrapper(localName = "getDaySupplyResponse", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetDaySupplyResponse")
    @Action(input = "urn:executeDaySupply", output = "http://services.walgreens.com/erx/DataEntryByPassService/ds/ErxDecisionServices/getDaySupplyResponse")
    public ErxTransaction getDaySupply(
        @WebParam(name = "arg0", targetNamespace = "")
        ErxTransaction arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.walgreens.services.erx.dataentrybypassservice.ds.ErxTransaction
     */
    @WebMethod(action = "urn:executeThirdParty")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getThirdParty", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetThirdParty")
    @ResponseWrapper(localName = "getThirdPartyResponse", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetThirdPartyResponse")
    @Action(input = "urn:executeThirdParty", output = "http://services.walgreens.com/erx/DataEntryByPassService/ds/ErxDecisionServices/getThirdPartyResponse")
    public ErxTransaction getThirdParty(
        @WebParam(name = "arg0", targetNamespace = "")
        ErxTransaction arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.walgreens.services.erx.dataentrybypassservice.ds.ErxTransaction
     */
    @WebMethod(action = "urn:executeDaySupplyAndThirdParty")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDaySupplyAndThirdParty", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetDaySupplyAndThirdParty")
    @ResponseWrapper(localName = "getDaySupplyAndThirdPartyResponse", targetNamespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", className = "com.walgreens.services.erx.dataentrybypassservice.ds.GetDaySupplyAndThirdPartyResponse")
    @Action(input = "urn:executeDaySupplyAndThirdParty", output = "http://services.walgreens.com/erx/DataEntryByPassService/ds/ErxDecisionServices/getDaySupplyAndThirdPartyResponse")
    public ErxTransaction getDaySupplyAndThirdParty(
        @WebParam(name = "arg0", targetNamespace = "")
        ErxTransaction arg0);

}
