//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.walgreens.services.erx.dataentrybypassservice.ds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ErxTransaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ErxTransaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prescription" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}Prescription"/>
 *         &lt;element name="substitutionDrugList" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}Drug" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patient" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}Patient" minOccurs="0"/>
 *         &lt;element name="transactionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="completionStatus" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}ResultType" minOccurs="0"/>
 *         &lt;element name="genericFor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="enableOrangeBookCheck" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="enableAutomation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="substitutedDrug" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}Drug" minOccurs="0"/>
 *         &lt;element name="annotations" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErxTransaction", propOrder = {
    "prescription",
    "substitutionDrugList",
    "patient",
    "transactionDateTime",
    "completionStatus",
    "genericFor",
    "enableOrangeBookCheck",
    "enableAutomation",
    "substitutedDrug",
    "annotations"
})
public class ErxTransaction {

    @XmlElement(required = true)
    protected Prescription prescription;
    protected List<Drug> substitutionDrugList;
    protected Patient patient;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar transactionDateTime;
    protected ResultType completionStatus;
    protected String genericFor;
    protected boolean enableOrangeBookCheck;
    protected boolean enableAutomation;
    protected Drug substitutedDrug;
    protected List<String> annotations;

    /**
     * Gets the value of the prescription property.
     * 
     * @return
     *     possible object is
     *     {@link Prescription }
     *     
     */
    public Prescription getPrescription() {
        return prescription;
    }

    /**
     * Sets the value of the prescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prescription }
     *     
     */
    public void setPrescription(Prescription value) {
        this.prescription = value;
    }

    /**
     * Gets the value of the substitutionDrugList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substitutionDrugList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstitutionDrugList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Drug }
     * 
     * 
     */
    public List<Drug> getSubstitutionDrugList() {
        if (substitutionDrugList == null) {
            substitutionDrugList = new ArrayList<Drug>();
        }
        return this.substitutionDrugList;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link Patient }
     *     
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Patient }
     *     
     */
    public void setPatient(Patient value) {
        this.patient = value;
    }

    /**
     * Gets the value of the transactionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTransactionDateTime() {
        return transactionDateTime;
    }

    /**
     * Sets the value of the transactionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTransactionDateTime(XMLGregorianCalendar value) {
        this.transactionDateTime = value;
    }

    /**
     * Gets the value of the completionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ResultType }
     *     
     */
    public ResultType getCompletionStatus() {
        return completionStatus;
    }

    /**
     * Sets the value of the completionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultType }
     *     
     */
    public void setCompletionStatus(ResultType value) {
        this.completionStatus = value;
    }

    /**
     * Gets the value of the genericFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericFor() {
        return genericFor;
    }

    /**
     * Sets the value of the genericFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericFor(String value) {
        this.genericFor = value;
    }

    /**
     * Gets the value of the enableOrangeBookCheck property.
     * 
     */
    public boolean isEnableOrangeBookCheck() {
        return enableOrangeBookCheck;
    }

    /**
     * Sets the value of the enableOrangeBookCheck property.
     * 
     */
    public void setEnableOrangeBookCheck(boolean value) {
        this.enableOrangeBookCheck = value;
    }

    /**
     * Gets the value of the enableAutomation property.
     * 
     */
    public boolean isEnableAutomation() {
        return enableAutomation;
    }

    /**
     * Sets the value of the enableAutomation property.
     * 
     */
    public void setEnableAutomation(boolean value) {
        this.enableAutomation = value;
    }

    /**
     * Gets the value of the substitutedDrug property.
     * 
     * @return
     *     possible object is
     *     {@link Drug }
     *     
     */
    public Drug getSubstitutedDrug() {
        return substitutedDrug;
    }

    /**
     * Sets the value of the substitutedDrug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drug }
     *     
     */
    public void setSubstitutedDrug(Drug value) {
        this.substitutedDrug = value;
    }

    /**
     * Gets the value of the annotations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAnnotations() {
        if (annotations == null) {
            annotations = new ArrayList<String>();
        }
        return this.annotations;
    }

}
