//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.walgreens.services.erx.dataentrybypassservice.ds;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.walgreens.services.erx.dataentrybypassservice.ds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetDrugSelectionResponse_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getDrugSelectionResponse");
    private final static QName _GetDaySupplyAndThirdParty_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getDaySupplyAndThirdParty");
    private final static QName _GetQuantity_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getQuantity");
    private final static QName _GetDrugSelectionAndQuantity_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getDrugSelectionAndQuantity");
    private final static QName _GetDaySupplyResponse_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getDaySupplyResponse");
    private final static QName _GetDrugSelectionAndQuantityResponse_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getDrugSelectionAndQuantityResponse");
    private final static QName _GetDaySupply_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getDaySupply");
    private final static QName _GetQuantityResponse_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getQuantityResponse");
    private final static QName _GetDrugSelection_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getDrugSelection");
    private final static QName _GetThirdParty_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getThirdParty");
    private final static QName _GetThirdPartyResponse_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getThirdPartyResponse");
    private final static QName _GetDaySupplyAndThirdPartyResponse_QNAME = new QName("http://services.walgreens.com/erx/DataEntryByPassService/ds", "getDaySupplyAndThirdPartyResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.walgreens.services.erx.dataentrybypassservice.ds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetQuantity }
     * 
     */
    public GetQuantity createGetQuantity() {
        return new GetQuantity();
    }

    /**
     * Create an instance of {@link GetDaySupplyAndThirdParty }
     * 
     */
    public GetDaySupplyAndThirdParty createGetDaySupplyAndThirdParty() {
        return new GetDaySupplyAndThirdParty();
    }

    /**
     * Create an instance of {@link GetQuantityResponse }
     * 
     */
    public GetQuantityResponse createGetQuantityResponse() {
        return new GetQuantityResponse();
    }

    /**
     * Create an instance of {@link GetDaySupplyAndThirdPartyResponse }
     * 
     */
    public GetDaySupplyAndThirdPartyResponse createGetDaySupplyAndThirdPartyResponse() {
        return new GetDaySupplyAndThirdPartyResponse();
    }

    /**
     * Create an instance of {@link GetThirdParty }
     * 
     */
    public GetThirdParty createGetThirdParty() {
        return new GetThirdParty();
    }

    /**
     * Create an instance of {@link GetDaySupply }
     * 
     */
    public GetDaySupply createGetDaySupply() {
        return new GetDaySupply();
    }

    /**
     * Create an instance of {@link GetThirdPartyResponse }
     * 
     */
    public GetThirdPartyResponse createGetThirdPartyResponse() {
        return new GetThirdPartyResponse();
    }

    /**
     * Create an instance of {@link GetDrugSelection }
     * 
     */
    public GetDrugSelection createGetDrugSelection() {
        return new GetDrugSelection();
    }

    /**
     * Create an instance of {@link GetDaySupplyResponse }
     * 
     */
    public GetDaySupplyResponse createGetDaySupplyResponse() {
        return new GetDaySupplyResponse();
    }

    /**
     * Create an instance of {@link GetDrugSelectionResponse }
     * 
     */
    public GetDrugSelectionResponse createGetDrugSelectionResponse() {
        return new GetDrugSelectionResponse();
    }

    /**
     * Create an instance of {@link GetDrugSelectionAndQuantity }
     * 
     */
    public GetDrugSelectionAndQuantity createGetDrugSelectionAndQuantity() {
        return new GetDrugSelectionAndQuantity();
    }

    /**
     * Create an instance of {@link GetDrugSelectionAndQuantityResponse }
     * 
     */
    public GetDrugSelectionAndQuantityResponse createGetDrugSelectionAndQuantityResponse() {
        return new GetDrugSelectionAndQuantityResponse();
    }

    /**
     * Create an instance of {@link Drug }
     * 
     */
    public Drug createDrug() {
        return new Drug();
    }

    /**
     * Create an instance of {@link Store }
     * 
     */
    public Store createStore() {
        return new Store();
    }

    /**
     * Create an instance of {@link Plan }
     * 
     */
    public Plan createPlan() {
        return new Plan();
    }

    /**
     * Create an instance of {@link ErxTransaction }
     * 
     */
    public ErxTransaction createErxTransaction() {
        return new ErxTransaction();
    }

    /**
     * Create an instance of {@link PreferredGenericProduct }
     * 
     */
    public PreferredGenericProduct createPreferredGenericProduct() {
        return new PreferredGenericProduct();
    }

    /**
     * Create an instance of {@link CalculatedValues }
     * 
     */
    public CalculatedValues createCalculatedValues() {
        return new CalculatedValues();
    }

    /**
     * Create an instance of {@link Fill }
     * 
     */
    public Fill createFill() {
        return new Fill();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link ProductCategory }
     * 
     */
    public ProductCategory createProductCategory() {
        return new ProductCategory();
    }

    /**
     * Create an instance of {@link Sig }
     * 
     */
    public Sig createSig() {
        return new Sig();
    }

    /**
     * Create an instance of {@link Prescription }
     * 
     */
    public Prescription createPrescription() {
        return new Prescription();
    }

    /**
     * Create an instance of {@link DrugConstraint }
     * 
     */
    public DrugConstraint createDrugConstraint() {
        return new DrugConstraint();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDrugSelectionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getDrugSelectionResponse")
    public JAXBElement<GetDrugSelectionResponse> createGetDrugSelectionResponse(GetDrugSelectionResponse value) {
        return new JAXBElement<GetDrugSelectionResponse>(_GetDrugSelectionResponse_QNAME, GetDrugSelectionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDaySupplyAndThirdParty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getDaySupplyAndThirdParty")
    public JAXBElement<GetDaySupplyAndThirdParty> createGetDaySupplyAndThirdParty(GetDaySupplyAndThirdParty value) {
        return new JAXBElement<GetDaySupplyAndThirdParty>(_GetDaySupplyAndThirdParty_QNAME, GetDaySupplyAndThirdParty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetQuantity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getQuantity")
    public JAXBElement<GetQuantity> createGetQuantity(GetQuantity value) {
        return new JAXBElement<GetQuantity>(_GetQuantity_QNAME, GetQuantity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDrugSelectionAndQuantity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getDrugSelectionAndQuantity")
    public JAXBElement<GetDrugSelectionAndQuantity> createGetDrugSelectionAndQuantity(GetDrugSelectionAndQuantity value) {
        return new JAXBElement<GetDrugSelectionAndQuantity>(_GetDrugSelectionAndQuantity_QNAME, GetDrugSelectionAndQuantity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDaySupplyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getDaySupplyResponse")
    public JAXBElement<GetDaySupplyResponse> createGetDaySupplyResponse(GetDaySupplyResponse value) {
        return new JAXBElement<GetDaySupplyResponse>(_GetDaySupplyResponse_QNAME, GetDaySupplyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDrugSelectionAndQuantityResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getDrugSelectionAndQuantityResponse")
    public JAXBElement<GetDrugSelectionAndQuantityResponse> createGetDrugSelectionAndQuantityResponse(GetDrugSelectionAndQuantityResponse value) {
        return new JAXBElement<GetDrugSelectionAndQuantityResponse>(_GetDrugSelectionAndQuantityResponse_QNAME, GetDrugSelectionAndQuantityResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDaySupply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getDaySupply")
    public JAXBElement<GetDaySupply> createGetDaySupply(GetDaySupply value) {
        return new JAXBElement<GetDaySupply>(_GetDaySupply_QNAME, GetDaySupply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetQuantityResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getQuantityResponse")
    public JAXBElement<GetQuantityResponse> createGetQuantityResponse(GetQuantityResponse value) {
        return new JAXBElement<GetQuantityResponse>(_GetQuantityResponse_QNAME, GetQuantityResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDrugSelection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getDrugSelection")
    public JAXBElement<GetDrugSelection> createGetDrugSelection(GetDrugSelection value) {
        return new JAXBElement<GetDrugSelection>(_GetDrugSelection_QNAME, GetDrugSelection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetThirdParty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getThirdParty")
    public JAXBElement<GetThirdParty> createGetThirdParty(GetThirdParty value) {
        return new JAXBElement<GetThirdParty>(_GetThirdParty_QNAME, GetThirdParty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetThirdPartyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getThirdPartyResponse")
    public JAXBElement<GetThirdPartyResponse> createGetThirdPartyResponse(GetThirdPartyResponse value) {
        return new JAXBElement<GetThirdPartyResponse>(_GetThirdPartyResponse_QNAME, GetThirdPartyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDaySupplyAndThirdPartyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.walgreens.com/erx/DataEntryByPassService/ds", name = "getDaySupplyAndThirdPartyResponse")
    public JAXBElement<GetDaySupplyAndThirdPartyResponse> createGetDaySupplyAndThirdPartyResponse(GetDaySupplyAndThirdPartyResponse value) {
        return new JAXBElement<GetDaySupplyAndThirdPartyResponse>(_GetDaySupplyAndThirdPartyResponse_QNAME, GetDaySupplyAndThirdPartyResponse.class, null, value);
    }

}
