//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.walgreens.services.erx.dataentrybypassservice.ds;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paymentModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="paymentModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="COB"/>
 *     &lt;enumeration value="COUPON"/>
 *     &lt;enumeration value="DISCOUNT_CARD"/>
 *     &lt;enumeration value="PRIMARY"/>
 *     &lt;enumeration value="UNSPECIFIED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "paymentModeType")
@XmlEnum
public enum PaymentModeType {

    COB,
    COUPON,
    DISCOUNT_CARD,
    PRIMARY,
    UNSPECIFIED;

    public String value() {
        return name();
    }

    public static PaymentModeType fromValue(String v) {
        return valueOf(v);
    }

}
