//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.walgreens.services.erx.dataentrybypassservice.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Prescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Prescription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="refillQualifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transmittedDrug" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}Drug" minOccurs="0"/>
 *         &lt;element name="sig" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}Sig" minOccurs="0"/>
 *         &lt;element name="fill" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}Fill" minOccurs="0"/>
 *         &lt;element name="ncltCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transmittedNdc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dispensedAsWritten" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="doNotFill" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberOfRefillsPrescribed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="originalDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="quantityPrescribed" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="refillBeforeDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="useAsDirected" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="store" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}Store"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Prescription", propOrder = {
    "refillQualifier",
    "transmittedDrug",
    "sig",
    "fill",
    "ncltCode",
    "transmittedNdc",
    "dispensedAsWritten",
    "doNotFill",
    "notes",
    "numberOfRefillsPrescribed",
    "originalDate",
    "quantityPrescribed",
    "refillBeforeDate",
    "useAsDirected",
    "store"
})
public class Prescription {

    protected String refillQualifier;
    protected Drug transmittedDrug;
    protected Sig sig;
    protected Fill fill;
    protected String ncltCode;
    protected String transmittedNdc;
    protected int dispensedAsWritten;
    protected Boolean doNotFill;
    protected String notes;
    protected int numberOfRefillsPrescribed;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar originalDate;
    protected double quantityPrescribed;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar refillBeforeDate;
    protected Boolean useAsDirected;
    @XmlElement(required = true)
    protected Store store;

    /**
     * Gets the value of the refillQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefillQualifier() {
        return refillQualifier;
    }

    /**
     * Sets the value of the refillQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefillQualifier(String value) {
        this.refillQualifier = value;
    }

    /**
     * Gets the value of the transmittedDrug property.
     * 
     * @return
     *     possible object is
     *     {@link Drug }
     *     
     */
    public Drug getTransmittedDrug() {
        return transmittedDrug;
    }

    /**
     * Sets the value of the transmittedDrug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drug }
     *     
     */
    public void setTransmittedDrug(Drug value) {
        this.transmittedDrug = value;
    }

    /**
     * Gets the value of the sig property.
     * 
     * @return
     *     possible object is
     *     {@link Sig }
     *     
     */
    public Sig getSig() {
        return sig;
    }

    /**
     * Sets the value of the sig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sig }
     *     
     */
    public void setSig(Sig value) {
        this.sig = value;
    }

    /**
     * Gets the value of the fill property.
     * 
     * @return
     *     possible object is
     *     {@link Fill }
     *     
     */
    public Fill getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fill }
     *     
     */
    public void setFill(Fill value) {
        this.fill = value;
    }

    /**
     * Gets the value of the ncltCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNcltCode() {
        return ncltCode;
    }

    /**
     * Sets the value of the ncltCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNcltCode(String value) {
        this.ncltCode = value;
    }

    /**
     * Gets the value of the transmittedNdc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmittedNdc() {
        return transmittedNdc;
    }

    /**
     * Sets the value of the transmittedNdc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmittedNdc(String value) {
        this.transmittedNdc = value;
    }

    /**
     * Gets the value of the dispensedAsWritten property.
     * 
     */
    public int getDispensedAsWritten() {
        return dispensedAsWritten;
    }

    /**
     * Sets the value of the dispensedAsWritten property.
     * 
     */
    public void setDispensedAsWritten(int value) {
        this.dispensedAsWritten = value;
    }

    /**
     * Gets the value of the doNotFill property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDoNotFill() {
        return doNotFill;
    }

    /**
     * Sets the value of the doNotFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDoNotFill(Boolean value) {
        this.doNotFill = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the numberOfRefillsPrescribed property.
     * 
     */
    public int getNumberOfRefillsPrescribed() {
        return numberOfRefillsPrescribed;
    }

    /**
     * Sets the value of the numberOfRefillsPrescribed property.
     * 
     */
    public void setNumberOfRefillsPrescribed(int value) {
        this.numberOfRefillsPrescribed = value;
    }

    /**
     * Gets the value of the originalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOriginalDate() {
        return originalDate;
    }

    /**
     * Sets the value of the originalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOriginalDate(XMLGregorianCalendar value) {
        this.originalDate = value;
    }

    /**
     * Gets the value of the quantityPrescribed property.
     * 
     */
    public double getQuantityPrescribed() {
        return quantityPrescribed;
    }

    /**
     * Sets the value of the quantityPrescribed property.
     * 
     */
    public void setQuantityPrescribed(double value) {
        this.quantityPrescribed = value;
    }

    /**
     * Gets the value of the refillBeforeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRefillBeforeDate() {
        return refillBeforeDate;
    }

    /**
     * Sets the value of the refillBeforeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRefillBeforeDate(XMLGregorianCalendar value) {
        this.refillBeforeDate = value;
    }

    /**
     * Gets the value of the useAsDirected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseAsDirected() {
        return useAsDirected;
    }

    /**
     * Sets the value of the useAsDirected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseAsDirected(Boolean value) {
        this.useAsDirected = value;
    }

    /**
     * Gets the value of the store property.
     * 
     * @return
     *     possible object is
     *     {@link Store }
     *     
     */
    public Store getStore() {
        return store;
    }

    /**
     * Sets the value of the store property.
     * 
     * @param value
     *     allowed object is
     *     {@link Store }
     *     
     */
    public void setStore(Store value) {
        this.store = value;
    }

}
