//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.walgreens.services.erx.dataentrybypassservice.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Store complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Store">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="state" type="{http://services.walgreens.com/erx/DataEntryByPassService/ds}StateType"/>
 *         &lt;element name="nabpNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inOrangeBookState" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Store", propOrder = {
    "state",
    "nabpNumber",
    "inOrangeBookState"
})
public class Store {

    @XmlElement(required = true)
    protected StateType state;
    @XmlElement(required = true)
    protected String nabpNumber;
    protected Boolean inOrangeBookState;

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link StateType }
     *     
     */
    public StateType getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateType }
     *     
     */
    public void setState(StateType value) {
        this.state = value;
    }

    /**
     * Gets the value of the nabpNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNabpNumber() {
        return nabpNumber;
    }

    /**
     * Sets the value of the nabpNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNabpNumber(String value) {
        this.nabpNumber = value;
    }

    /**
     * Gets the value of the inOrangeBookState property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInOrangeBookState() {
        return inOrangeBookState;
    }

    /**
     * Sets the value of the inOrangeBookState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInOrangeBookState(Boolean value) {
        this.inOrangeBookState = value;
    }

}
